set_property SRC_FILE_INFO {cfile:C:/Users/SUPRITH/Thesis10/Thesis10.srcs/constrs_1/new/const.xdc rfile:../../../Thesis10.srcs/constrs_1/new/const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports pin1]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U12 [get_ports led]
